### PR TITLE
Added console library if needed to run single cpp program

### PR DESCRIPTION
**Pull request by FA-CZ**
Tried to add Console library to enhance any use of c++ program alone if rectified.
Thank You for Project

### CODE REVIEW

**Comment by JusticeRage** [comment]
Thanks for contributing!
I don't really understand what your commit does, can you explain why it is needed?

**Comment by FA-CZ** [comment]
It was a basic editing, which will make it more apealing to the next person
who will pull request from your repository. It is well coded, the only
thing was a bit editing in its apealing look. Thanks for contacting me, it
was very nice to converse with you.

**Comment by JusticeRage** [comment]
Thanks again for contributing.
I'm not sure that this PR adds a meaningful feature to the project however, so I think I will not merge it.

**Comment by FA-CZ** [comment]
I added console library so that if any anomaly working happens, one will be
able to rectify by the output it can give. This was my contribution to add
console library.
Thank you

**Pull request closed without merging**
